# -*- coding: utf-8 -*-
"""Dz support_vector_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uyH0eXk9OsHkb2Z3K25WnXW7YyGUJ_7y

# Support Vector Regression (SVR)

## Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

print(x)

print(y)

y = y.reshape(len(y),1)

print(y)

"""## Feature Scaling"""

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
x = sc_x.fit_transform(x)
y = sc_y.fit_transform(y)

print(x)

print(y)

"""## Training the SVR model on the whole dataset"""

from sklearn.svm import SVR
regressor = SVR( kernel = 'rbf' )
regressor.fit(x,y)

"""## Predicting a new result"""

pred_lvl6p5 = sc_y.inverse_transform(regressor.predict(sc_x.transform([[6.5]])).reshape(-1,1))

"""## Visualising the SVR results"""

plt.scatter(sc_x.inverse_transform(x), sc_y.inverse_transform(y), color = 'red')
plt.plot(sc_x.inverse_transform(x), sc_y.inverse_transform(regressor.predict(x).reshape(-1,1)), color = 'blue')
plt.title('SVR Results')
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()

"""## Visualising the SVR results (for higher resolution and smoother curve)"""

X_grid = np.arange(min(sc_x.inverse_transform(x)), max(sc_x.inverse_transform(x)), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(sc_x.inverse_transform(x), sc_y.inverse_transform(y), color = 'red')
plt.plot(X_grid, sc_y.inverse_transform(regressor.predict(sc_x.transform(X_grid)).reshape(-1,1)), color = 'blue')
plt.title('SVR')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()